name: Laredo Scraper

on:
  workflow_dispatch:
    inputs:
      headless:
        description: "Run headless"
        type: boolean
        default: true
      out_dir:
        description: "Output directory"
        type: string
        default: "files"
      wait_seconds:
        description: "UI wait seconds"
        type: number
        default: 30
      max_parties:
        description: "How many Party columns (Party1..N)"
        type: number
        default: 6
      rescrape_indices:
        description: "Space-separated county indices for second pass (e.g. '1 2')"
        type: string
        default: "1 2"
      days_back:
        description: "Skip rows with Doc Date older than N days (0 to disable)"
        type: number
        default: 2
      start_url:
        description: "Direct URL to results table page (recommended)"
        type: string
        default: ""
      push_results:
        description: "Commit JSON/results back to repo"
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      LAREDO_USERNAME: ${{ secrets.LAREDO_USERNAME }}
      LAREDO_PASSWORD: ${{ secrets.LAREDO_PASSWORD }}
      # If you want, you can store a default in a secret and fall back to it:
      LAREDO_URL: ${{ secrets.LAREDO_URL }}
      OUT_DIR: ${{ inputs.out_dir || 'files' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Ensure output directory exists (and keep it in git)
        run: |
          mkdir -p "${{ env.OUT_DIR }}"
          echo "keep" > "${{ env.OUT_DIR }}/.gitkeep"

      - name: Run scraper
        run: |
          echo "Rescrape indices: ${{ inputs.rescrape_indices }}"
          python laredo_scraper.py \
            ${{ inputs.headless && '--headless' || '' }} \
            --out "${{ env.OUT_DIR }}" \
            --wait ${{ inputs.wait_seconds }} \
            --max-parties ${{ inputs.max_parties }} \
            --days-back ${{ inputs.days_back }} \
            --rescrape-indices "${{ inputs.rescrape_indices }}" \
            --start-url "${{ inputs.start_url || env.LAREDO_URL }}"

      - name: List outputs for debugging
        if: always()
        run: |
          echo "=== GIT STATUS ==="
          git status
          echo "=== TREE (repo root) ==="
          ls -la
          echo "=== OUT_DIR LISTING ==="
          ls -la "${{ env.OUT_DIR }}" || true
          echo "=== LOG PREVIEW ==="
          tail -n 200 laredo.logs || true
          echo "=== Flow log preview ==="
          tail -n 200 laredo-flow-logs.json || true
          echo "=== If present, saved HTML title ==="
          python - <<'PY'
import os, re
p="laredo_page.html"
if os.path.exists(p):
    import bs4
    from bs4 import BeautifulSoup
    with open(p, "r", encoding="utf-8", errors="ignore") as f:
        s=BeautifulSoup(f, "html.parser")
        print("HTML <title>:", (s.title.string if s.title else "").strip())
else:
    print("No laredo_page.html saved")
PY
          echo "=== If present, screenshot file size ==="
          [ -f laredo_page.png ] && ls -la laredo_page.png || echo "No laredo_page.png saved"

      - name: Upload JSON, logs, HTML and screenshot as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: laredo-results
          path: |
            ${{ env.OUT_DIR }}/
            laredo-flow-logs.json
            laredo.logs
            laredo_page.html
            laredo_page.png

      - name: Commit results to repo
        if: ${{ inputs.push_results }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Force-add even if patterns are in .gitignore
          git add -f "${{ env.OUT_DIR }}/.gitkeep" 2>/dev/null || true
          git add -f "${{ env.OUT_DIR }}"/*.json 2>/dev/null || true
          git add -f "${{ env.OUT_DIR }}"/*.csv 2>/dev/null || true
          git add -f laredo-flow-logs.json laredo.logs 2>/dev/null || true
          git add -f laredo_page.html laredo_page.png 2>/dev/null || true

          git commit -m "chore: update Laredo outputs $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push || true
